services:
  frontend:
    build: ./frontend
    container_name: archi_frontend
    ports:
      - "3000:3000"
    networks:
      - archi_net
    depends_on:
      - auth-service

  auth-service:
    build: ./auth-service
    container_name: archi_auth
    ports:
      - "3002:3002"
    networks:
      - archi_net

  user-service:
    build: ./user-service
    container_name: archi_user
    ports:
      - "3001:3001"
    networks:
      - archi_net

  document-service:
    build: ./document-service
    container_name: archi_document
    ports:
      - "3003:3003"
    networks:
      - archi_net
    depends_on:
      - minio

  nginx:
    image: nginx:stable
    container_name: archi_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - archi_net
    depends_on:
      - frontend
      - auth-service

  minio:
    image: minio/minio
    container_name: archi_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - archi_net

  auth_postgres:
    image: postgres:15
    container_name: auth_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authdb
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - archi_net


  user_postgres:
    image: postgres:15
    container_name: user_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: userdb
    volumes:
      - user_postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - archi_net

  document_postgres:
    image: postgres:15
    container_name: document_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: documentdb
    volumes:
      - document_postgres_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    networks:
      - archi_net


volumes:
  minio_data:
  auth_postgres_data:
  user_postgres_data:
  document_postgres_data:

networks:
  archi_net:
    driver: bridge