services:
  frontend:
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env.docker
    ports:
      - "3100:3100"
    command: npm run dev

  auth-service:
    volumes:
      - ./auth-service:/app
      - /app/node_modules
    env_file:
      - ./auth-service/.env.docker
    ports:
      - "3001:3001"
    command: npm run start:dev

  user-service:
    volumes:
      - ./user-service:/app
      - /app/node_modules
    env_file:
      - ./user-service/.env.docker
    ports:
      - "3002:3002"
    command: npm run start:dev

  bff-service:
    volumes:
      - ./bff-service:/app
      - /app/node_modules
    env_file:
      - ./bff-service/.env.docker
    ports:
      - "3000:3000"
    command: npm run start:dev

  document-service:
    volumes:
      - ./document-service:/app
      - /app/node_modules
    env_file:
      - ./document-service/.env.docker
    ports:
      - "3003:3003"
    command: npm run start:dev