services:
  nginx:
    image: nginx:stable
    container_name: archi_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./letsencrypt:/var/www/letsencrypt:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - bff-service
      - auth-service
      - user-service
      - document-service
    networks:
      - archi_net

  frontend:
    image: ghcr.io/kushumai/archi/frontend:latest 
    env_file:
      - ./frontend/.env
    command: npm run start
    networks:
      - archi_net

  bff-service:
    image: ghcr.io/kushumai/archi/bff-service:latest
    env_file:
      - ./bff-service/.env
    command: node dist/main.js
    networks:
      - archi_net

  auth-service:
    image: ghcr.io/kushumai/archi/auth-service:latest
    env_file:
      - ./auth-service/.env
    command: sh -c "npx prisma migrate deploy && node dist/main.js"
    networks:
      - archi_net

  user-service:
    image: ghcr.io/kushumai/archi/user-service:latest
    env_file:
      - ./user-service/.env
    command: sh -c "npx prisma migrate deploy && node dist/main.js"
    networks:
      - archi_net

  document-service:
    image: ghcr.io/kushumai/archi/document-service:latest
    env_file:
      - ./document-service/.env
    command: sh -c "npx prisma migrate deploy && node dist/main.js"
    networks:
      - archi_net

  minio:
    image: minio/minio
    container_name: archi_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - archi_net

  auth_postgres:
    image: postgres:15
    container_name: auth_postgres
    restart: always
    environment:
      POSTGRES_USER: ${AUTH_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUTH_POSTGRES_PASSWORD}
      POSTGRES_DB: ${AUTH_POSTGRES_DB}
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432" 
    networks:
      - archi_net

  user_postgres:
    image: postgres:15
    container_name: user_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DOCUMENT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DOCUMENT_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DOCUMENT_POSTGRES_DB}
    volumes:
      - user_postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432" 
    networks:
      - archi_net

  document_postgres:
    image: postgres:15
    container_name: document_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DOCUMENT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DOCUMENT_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DOCUMENT_POSTGRES_DB}
    volumes:
      - document_postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432" 
    networks:
      - archi_net

volumes:
  minio_data:
  auth_postgres_data:
  user_postgres_data:
  document_postgres_data:

networks:
  archi_net:
    driver: bridge
