networks:
  prod_net: {}

services:
  # Backend (NestJS)
  backend:
    build:
      context: ../../backend
      dockerfile: ../docker/prod/Dockerfile.backend
    ports:
      - "3000:3000"
    env_file:
      - ../../backend/.env
    environment:
      NODE_ENV: production
    depends_on:
      - postgres
      - mongo
    networks:
    - prod_net
    container_name: archi_backend_prod

  # Frontend (React.js)
  frontend:
    build:
      context: ../../frontend
      dockerfile: ../docker/prod/Dockerfile.frontend
    ports:
      - "80:80"
    environment:
      NODE_ENV: production
    depends_on:
      - backend
    networks:
    - prod_net
    container_name: archi_frontend_prod

  # PostgreSQL
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: psql_archi_db
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
    - prod_net
    container_name: archi_postgres_prod

  # MongoDB
  mongo:
    image: mongo:5
    # ports:
    #   - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: mg_archi_db
    networks:
    - prod_net
    container_name: archi_mongo_prod

volumes:
  postgres_data: {}
  mongo_data: {}