FROM node:16-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN apk update && apk upgrade
RUN npm run build
FROM node:16-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install --only=production
COPY --from=builder /app/dist ./dist
# COPY --from=builder /app/.env ./
EXPOSE 3000
CMD ["npm", "run", "start:prod"]