name: CI Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_PREFIX: ${{ github.repository }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready" --health-interval=10s
          --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Build code
        run: npm run build

      - name: Run unit tests
        run: npm test

  docker-build:
    runs-on: ubuntu-latest
    needs: build-and-test
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        run: |
          docker build -t ghcr.io/${{ github.repository }}/frontend:latest ./frontend
          docker push ghcr.io/${{ github.repository }}/frontend:latest

          docker build -t ghcr.io/${{ github.repository }}/auth-service:latest ./auth-service
          docker push ghcr.io/${{ github.repository }}/auth-service:latest

          docker build -t ghcr.io/${{ github.repository }}/user-service:latest ./user-service
          docker push ghcr.io/${{ github.repository }}/user-service:latest

          docker build -t ghcr.io/${{ github.repository }}/document-service:latest ./document-service
          docker push ghcr.io/${{ github.repository }}/document-service:latest

          docker build -t ghcr.io/${{ github.repository }}/bff-service:latest ./bff-service
          docker push ghcr.io/${{ github.repository }}/bff-service:latest